export const PRODUCT_TYPE_SPECS = {
  cpu: [
    { name: 'cpuCores', label: 'Số nhân', type: 'number', options: ['2', '4', '6', '8', '12', '16', '24', '32', '64'] },
    { name: 'cpuThreads', label: 'Số luồng', type: 'number', options: ['4', '6', '8', '12', '16', '24', '32', '64'] },
    { name: 'cpuSocket', label: 'Socket', type: 'text', options: ['AM4', 'AM5', 'LGA1200', 'LGA1700'] },
    { name: 'cpuBaseSpeed', label: 'Tốc độ cơ bản (GHz)', type: 'number' },
    { name: 'cpuBoostSpeed', label: 'Tốc độ tối đa (GHz)', type: 'number' },
    { name: 'cpuCache', label: 'Bộ nhớ đệm (MB)', type: 'number' },
    { name: 'cpuTdp', label: 'TDP (W)', type: 'number' },
  ],
  vga: [
    { name: 'vgaVram', label: 'Bộ nhớ (GB)', type: 'number' },
    { name: 'vgaVramType', label: 'Loại bộ nhớ', type: 'text', options: ['GDDR5', 'GDDR6', 'GDDR6X', 'HBM2'] },
    { name: 'vgaBoostSpeed', label: 'Tốc độ xung nhịp tối đa (MHz)', type: 'number' },
    { name: 'vgaPCIExpress', label: 'Chuẩn PCI Express', type: 'text', options: ['PCIe 3.0', 'PCIe 4.0', 'PCIe 5.0'] },
    { name: 'vgaDisplayPorts', label: 'Số cổng DisplayPort', type: 'number' },
    { name: 'vgaHdmiPorts', label: 'Số cổng HDMI', type: 'number' },
    { name: 'vgaVgaPorts', label: 'Số cổng VGA', type: 'number' },
    { name: 'vgaDviPorts', label: 'Số cổng DVI', type: 'number' },
    { name: 'vga6PinConnectors', label: 'Số cổng 6-pin', type: 'number' },
    { name: 'vga6Plus2PinConnectors', label: 'Số cổng 6+2-pin', type: 'number' },
    { name: 'vga8PinConnectors', label: 'Số cổng 8-pin', type: 'number' },
    { name: 'vga12PinConnectors', label: 'Số cổng 12-pin', type: 'number' },
    { name: 'vgaMaxTDP', label: 'TDP tối đa (W)', type: 'number' },
    { name: 'vgaSize', label: 'Kích thước (mm)', type: 'text' },
  ],
  ram: [
    { name: 'ramCapacity', label: 'Dung lượng (GB)', type: 'number', options: ['4', '8', '16', '32', '64', '128', '256', '512'] },
    { name: 'ramType', label: 'Loại RAM', type: 'text', options: ['DDR3', 'DDR4', 'DDR5'] },
    { name: 'ramSpeed', label: 'Tốc độ (MHz)', type: 'number', options: ['2133', '2400', '2666', '2933', '3200', '3600', '4000'] },
    { name: 'ramLatency', label: 'Độ trễ (ns)', type: 'number' },
  ],
  ssd: [
    { name: 'ssdCapacity', label: 'Dung lượng (GB)', type: 'number' },
    { name: 'ssdType', label: 'Loại SSD', type: 'text', options: ['SATA', 'M.2 SATA', 'M.2 NVMe (PCIe)', 'PCIe'] },
    { name: 'ssdInterface', label: 'Chuẩn kết nối', type: 'text', options: ['SATA', 'PCIe 3.0', 'PCIe 4.0', 'PCIe 5.0', 'mSATA'] },
    { name: 'ssdFormFactor', label: 'Kích thước', type: 'text', options: ['2.5-inch', '22x80', '22x42', '22x30', '22x110', 'mSATA', 'Add-in Card'] },
    { name: 'ssdReadSpeed', label: 'Tốc độ đọc (MB/s)', type: 'number' },
    { name: 'ssdWriteSpeed', label: 'Tốc độ ghi (MB/s)', type: 'number' },
  ],
  hdd: [
    { name: 'hddCapacity', label: 'Dung lượng (GB)', type: 'number' },
    { name: 'hddFormFactor', label: 'Kích thước', type: 'text', options: ['3.5-inch', '2.5-inch'] },
    { name: 'hddInterface', label: 'Chuẩn kết nối', type: 'text', options: ['SATA III', 'SAS'] },
    { name: 'hddRpm', label: 'Tốc độ quay (RPM)', type: 'text', options: ['5400', '5900', '7200', '10000', '15000'] },
    { name: 'hddCache', label: 'Bộ nhớ đệm (MB)', type: 'text', options: ['32', '64', '128', '256', '512'] },
  ],
  mainboard: [
    { name: 'mainboardChipset', label: 'Chipset', type: 'text', options: ['A Series', 'B Series', 'X Series', 'H Series', 'Z Series'] },
    { name: 'mainboardSocket', label: 'Socket', type: 'text', options: ['AM4', 'AM5', 'LGA 1200', 'LGA 1700'] },
    { name: 'mainboardMemorySlots', label: 'Khe RAM', type: 'number' },
    { name: 'mainboardMaxMemory', label: 'Bộ nhớ tối đa (GB)', type: 'number' },
    { name: 'mainboardExpansionSlots', label: 'Khe mở rộng', type: 'text' },
    { name: 'mainboardStorage', label: 'Kết nối lưu trữ', type: 'text' },
  ],
  psu: [
    { name: 'psuWattage', label: 'Công suất (W)', type: 'number', options: ['400', '450', '500', '550', '600', '650', '700', '750', '800', '850', '1000', '1200', '1300', '1600'] },
    { name: 'psuEfficiency', label: 'Hiệu suất', type: 'text', options: ['80 Plus', '80 Plus Bronze', '80 Plus Silver', '80 Plus Gold', '80 Plus Platinum', '80 Plus Titanium'] },
    { name: 'psuModular', label: 'Loại dây cáp', type: 'text', options: ['Non-modular', 'Semi-modular', 'Full-modular'] },
  ],
  case: [
    { name: 'caseFormFactor', label: 'Kích thước', type: 'text', options: ['Mini-ITX', 'Micro-ATX', 'ATX', 'E-ATX'] },
    { name: 'caseMaterial', label: 'Chất liệu', type: 'text', options: ['Steel', 'Aluminum', 'Plastic', 'Tempered Glass'] },
    { name: 'caseExpansionSlots', label: 'Khe mở rộng', type: 'number' },
    { name: 'caseFans', label: 'Quạt tản nhiệt', type: 'number' },
  ],
  monitor: [
    { name: 'monitorSize', label: 'Kích thước màn hình (inch)', type: 'number' },
    { name: 'monitorResolution', label: 'Độ phân giải', type: 'text', options: ['1920x1080', '2560x1440', '3840x2160', '5120x2880'] },
    { name: 'monitorRefreshRate', label: 'Tần số quét (Hz)', type: 'number', options: ['60', '75', '120', '144', '165', '240'] },
    { name: 'monitorPanelType', label: 'Loại tấm nền', type: 'text', options: ['IPS', 'TN', 'VA', 'OLED'] },
    { name: 'monitorResponseTime', label: 'Thời gian phản hồi (ms)', type: 'number', options: ['1', '2', '4', '5', '8'] },
  ],
  other: [
    { name: 'detail', label: 'Chi tiết', type: 'text' },
  ],
};

export const PRODUCT_TYPES = Object.keys(PRODUCT_TYPE_SPECS); 